/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adrover.antiads.panels;

import adrover.antiads.Main;
import adrover.antiads.use.AppColor;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Preferences and configuration panel of the application.
 * <p>
 * This panel allows the user to configure application settings such as:
 * </p>
 * <ul>
 * <li>Default download directory</li>
 * <li>Download speed configuration</li>
 * <li>Location of the {@code yt-dlp} executable</li>
 * </ul>
 *
 * <p>
 * The panel supports light and dark themes and automatically resizes its
 * components proportionally when the window size changes.
 * </p>
 *
 * @author Nuria
 * @version 1.0
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Base panel size used as reference for automatic resizing.
     */
    private final Dimension baseSize = new Dimension(800, 600);

    /**
     * Stores original component bounds for proportional resizing.
     */
    private final Map<Component, Rectangle> baseBounds = new HashMap<>();

    /**
     * Creates a new {@code EditPanel}.
     *
     * @param darkMode {@code true} to apply dark theme, {@code false} for light
     * theme
     */
    public EditPanel(boolean darkMode) {
        initComponents();
        this.setSize(800, 600);
        enableAutoResize();

        // Fuentes
        Font titleFont = new Font("Segoe UI", Font.BOLD, 28);
        Font labelFont = new Font("Segoe UI", Font.PLAIN, 16);
        Font textFieldFont = new Font("Segoe UI", Font.PLAIN, 14);
        Font buttonFont = new Font("Segoe UI", Font.BOLD, 14);

        // Labels
        jLabelTitle.setFont(titleFont);
        jLabelPath.setFont(labelFont);
        jLabelSpeed.setFont(labelFont);
        jLabelYtDlp.setFont(labelFont);

        // TextFields
        jTextFieldPath.setFont(textFieldFont);
        jSpinnerTime.setFont(textFieldFont);
        jTextFieldYtDlp.setFont(textFieldFont);

        // Botones
        jButtonBrowse.setFont(buttonFont);
        jButtonBack.setFont(buttonFont);

        // Opcional: cambiar estilo de los botones (por ejemplo, sin foco y borde plano)
        jButtonBrowse.setFocusPainted(false);
        jButtonBack.setFocusPainted(false);
        jButtonBrowse.setBorder(BorderFactory.createRaisedBevelBorder());
        jButtonBack.setBorder(BorderFactory.createRaisedBevelBorder());
        applyTheme(darkMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelPath = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jLabelSpeed = new javax.swing.JLabel();
        jLabelYtDlp = new javax.swing.JLabel();
        jTextFieldYtDlp = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jSpinnerTime = new javax.swing.JSpinner();

        setLayout(null);

        jLabelTitle.setText("Preferences");
        add(jLabelTitle);
        jLabelTitle.setBounds(320, 20, 220, 30);

        jLabelPath.setText("Path");
        add(jLabelPath);
        jLabelPath.setBounds(200, 60, 320, 40);

        jTextFieldPath.setText("C:\\Users\\nuria\\Downloads");
        add(jTextFieldPath);
        jTextFieldPath.setBounds(200, 100, 250, 40);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        add(jButtonBrowse);
        jButtonBrowse.setBounds(460, 100, 90, 30);

        jLabelSpeed.setText("Speed:");
        add(jLabelSpeed);
        jLabelSpeed.setBounds(270, 270, 60, 30);

        jLabelYtDlp.setText("Location of yt-dlp binary:");
        add(jLabelYtDlp);
        jLabelYtDlp.setBounds(200, 160, 210, 20);

        jTextFieldYtDlp.setText("C:\\Users\\nuria\\AppData\\Local\\yt-dlp\\yt-dlp.exe");
        add(jTextFieldYtDlp);
        jTextFieldYtDlp.setBounds(200, 190, 340, 40);

        jButtonBack.setText("Return");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(320, 370, 110, 40);

        jSpinnerTime.setModel(new javax.swing.SpinnerNumberModel(5, null, null, 1));
        add(jSpinnerTime);
        jSpinnerTime.setBounds(320, 270, 70, 30);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Applies the selected visual theme to the panel.
     *
     * @param darkMode {@code true} for dark theme, {@code false} for light
     * theme
     */
    public void applyTheme(boolean darkMode) {

        Color bg = darkMode ? AppColor.DARK_BG : AppColor.LIGHT_BG;
        Color panel = darkMode ? AppColor.DARK_PANEL : AppColor.LIGHT_PANEL;
        Color btn = darkMode ? AppColor.DARK_BUTTON : AppColor.LIGHT_BUTTON;
        Color text = darkMode ? AppColor.DARK_TEXT : AppColor.LIGHT_TEXT;

        // Fondo del panel
        setBackground(bg);

        // Labels
        jLabelTitle.setForeground(text);
        jLabelPath.setForeground(text);
        jLabelSpeed.setForeground(text);
        jLabelYtDlp.setForeground(text);

        // TextFields
        jTextFieldPath.setBackground(panel);
        jTextFieldPath.setForeground(text);

        jTextFieldYtDlp.setBackground(panel);
        jTextFieldYtDlp.setForeground(text);

        // Botones
        jButtonBrowse.setBackground(btn);
        jButtonBrowse.setForeground(text);

        jButtonBack.setBackground(btn);
        jButtonBack.setForeground(text);

        repaint();
    }

    /**
     * Enables proportional automatic resizing of all panel components.
     * <p>
     * Component bounds are recalculated based on the original panel size.
     * </p>
     */
    private void enableAutoResize() {

        // Guardar bounds originales
        for (Component c : getComponents()) {
            baseBounds.put(c, c.getBounds());
        }

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {

                double scaleX = getWidth() / (double) baseSize.width;
                double scaleY = getHeight() / (double) baseSize.height;

                for (Map.Entry<Component, Rectangle> entry : baseBounds.entrySet()) {

                    Component c = entry.getKey();
                    Rectangle r = entry.getValue();

                    int newX = (int) (r.x * scaleX);
                    int newY = (int) (r.y * scaleY);
                    int newW = (int) (r.width * scaleX);
                    int newH = (int) (r.height * scaleY);

                    c.setBounds(newX, newY, newW, newH);
                }

                revalidate();
                repaint();
            }
        });

        // 🔁 Recalcular bounds reales una vez pintado
        SwingUtilities.invokeLater(() -> {
            baseBounds.clear();
            for (Component c : getComponents()) {
                baseBounds.put(c, c.getBounds());
            }
        });
    }

    /**
     * Opens a directory chooser to select the download path.
     *
     * @param evt action event triggered by the browse button
     */
    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldPath.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    /**
     * Returns to the main application panel.
     *
     * @param evt action event triggered by the return button
     */
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (topFrame instanceof Main mainFrame) {
            mainFrame.setContentPane(mainFrame.mainPanel);
            mainFrame.revalidate();
            mainFrame.repaint();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JLabel jLabelPath;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelYtDlp;
    private javax.swing.JSpinner jSpinnerTime;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JTextField jTextFieldYtDlp;
    // End of variables declaration//GEN-END:variables
}
