/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adrover.antiads;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nuria
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
        this.setSize(800, 600);
       // jTextFieldYtDlp("C:\\Users\\nuria\\AppData\\Local\\yt-dlp\\yt-dlp.exe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelPath = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jLabelSpeed = new javax.swing.JLabel();
        jTextFieldSpeed = new javax.swing.JTextField();
        jLabelYtDlp = new javax.swing.JLabel();
        jTextFieldYtDlp = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setLayout(null);

        jLabelTitle.setText("Preferences");
        add(jLabelTitle);
        jLabelTitle.setBounds(320, 20, 220, 30);

        jLabelPath.setText("Path");
        add(jLabelPath);
        jLabelPath.setBounds(40, 60, 320, 40);

        jTextFieldPath.setText("C:\\Users\\nuria\\Downloads");
        add(jTextFieldPath);
        jTextFieldPath.setBounds(40, 100, 250, 40);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        add(jButtonBrowse);
        jButtonBrowse.setBounds(100, 150, 90, 20);

        jLabelSpeed.setText("Speed:");
        add(jLabelSpeed);
        jLabelSpeed.setBounds(30, 180, 250, 30);

        jTextFieldSpeed.setText("5");
        jTextFieldSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSpeedActionPerformed(evt);
            }
        });
        add(jTextFieldSpeed);
        jTextFieldSpeed.setBounds(30, 220, 280, 50);

        jLabelYtDlp.setText("Location of yt-dlp binary:");
        add(jLabelYtDlp);
        jLabelYtDlp.setBounds(400, 160, 210, 20);

        jTextFieldYtDlp.setText("C:\\Users\\nuria\\AppData\\Local\\yt-dlp\\yt-dlp.exe");
        add(jTextFieldYtDlp);
        jTextFieldYtDlp.setBounds(400, 190, 340, 40);

        jButtonBack.setText("Return");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(320, 340, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldPath.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (topFrame instanceof Main mainFrame) {
            mainFrame.setContentPane(mainFrame.mainPanel);
            mainFrame.revalidate();
            mainFrame.repaint();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSpeedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JLabel jLabelPath;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelYtDlp;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JTextField jTextFieldSpeed;
    private javax.swing.JTextField jTextFieldYtDlp;
    // End of variables declaration//GEN-END:variables
}
