/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adrover.antiads;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nuria
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
        this.setSize(800, 600);
        setBackground(new Color(173, 216, 230)); // Light blue

        // 🧩 Fonts and text
        Font font = new Font("Leelawadee UI", Font.PLAIN, 14);
        jLabelTitle.setText("Preferences");
        jLabelTitle.setFont(new Font("Leelawadee UI", Font.BOLD, 22));

        jLabelPath.setText("Path for temporary downloaded files:");
        jLabelPath.setFont(font);

        jLabelSpeed.setText("Limit download speed (MB/s):");
        jLabelSpeed.setFont(font);

        jLabelYtDlp.setText("Location of yt-dlp binary:");
        jLabelYtDlp.setFont(font);

        jCheckBoxM3U.setText("Create .m3u file for playlists");
        jCheckBoxM3U.setBackground(new Color(173, 216, 230));
        jCheckBoxM3U.setFont(font);

        jButtonBrowse.setText("Browse...");
        jButtonBack.setText("Back");
        jButtonBrowse.setFont(font);
        jButtonBack.setFont(font);

        jTextFieldPath.setText("C:\\Users\\nuria\\Downloads\\Temp");
        jTextFieldSpeed.setText("5");
        jTextFieldYtDlp.setText("C:\\Users\\nuria\\AppData\\Local\\yt-dlp\\yt-dlp.exe");
        jTextFieldPath.setFont(font);
        jTextFieldSpeed.setFont(font);
        jTextFieldYtDlp.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelPath = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jCheckBoxM3U = new javax.swing.JCheckBox();
        jLabelSpeed = new javax.swing.JLabel();
        jTextFieldSpeed = new javax.swing.JTextField();
        jLabelYtDlp = new javax.swing.JLabel();
        jTextFieldYtDlp = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setLayout(null);

        jLabelTitle.setText("title");
        add(jLabelTitle);
        jLabelTitle.setBounds(320, 20, 220, 30);

        jLabelPath.setText("path");
        add(jLabelPath);
        jLabelPath.setBounds(40, 60, 320, 40);

        jTextFieldPath.setText("jTextField1");
        add(jTextFieldPath);
        jTextFieldPath.setBounds(40, 100, 250, 40);

        jButtonBrowse.setText("jButton1");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        add(jButtonBrowse);
        jButtonBrowse.setBounds(500, 210, 90, 30);

        jCheckBoxM3U.setText("jCheckBox1");
        jCheckBoxM3U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxM3UActionPerformed(evt);
            }
        });
        add(jCheckBoxM3U);
        jCheckBoxM3U.setBounds(400, 70, 290, 40);

        jLabelSpeed.setText("jLabel1");
        add(jLabelSpeed);
        jLabelSpeed.setBounds(40, 160, 250, 30);

        jTextFieldSpeed.setText("jTextField1");
        add(jTextFieldSpeed);
        jTextFieldSpeed.setBounds(30, 200, 280, 50);

        jLabelYtDlp.setText("jLabel1");
        add(jLabelYtDlp);
        jLabelYtDlp.setBounds(400, 110, 210, 20);

        jTextFieldYtDlp.setText("jTextField1");
        add(jTextFieldYtDlp);
        jTextFieldYtDlp.setBounds(400, 140, 340, 40);

        jButtonBack.setText("jButton1");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(320, 340, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldPath.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (topFrame instanceof Main mainFrame) {
            mainFrame.setContentPane(mainFrame.mainPanel);
            mainFrame.revalidate();
            mainFrame.repaint();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jCheckBoxM3UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxM3UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxM3UActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JCheckBox jCheckBoxM3U;
    private javax.swing.JLabel jLabelPath;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelYtDlp;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JTextField jTextFieldSpeed;
    private javax.swing.JTextField jTextFieldYtDlp;
    // End of variables declaration//GEN-END:variables
}
