/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrover.antiads;

import adrover.antiads.panels.EditPanel;
import adrover.antiads.panels.DetailsPanel;
import adrover.antiads.dialogs.AboutDialog;
import adrover.antiads.login.LoginPanel;
import adrover.antiads.login.TokenManager;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author nuria
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    public javax.swing.JPanel mainPanel;
    private EditPanel editPanel;
    private java.io.File lastDownloadedFile;
    private DetailsPanel detailsPanel;
    private LoginPanel loginPanel;

    //nuriadrover@di03.com
    public Main() {
        initComponents();
        this.setSize(800, 600);
        setLocationRelativeTo(this);

        mainPanel = (JPanel) getContentPane();

        // Create login panel with callback
        loginPanel = new LoginPanel(() -> showMainPanel());

        // Initialize other panels
        detailsPanel = new DetailsPanel();
        editPanel = new EditPanel();

        // Auto-login
        SwingUtilities.invokeLater(() -> {
            if (!tryAutoLogin()) {
                showLoginPanel();
            }
        });

        jButtonDetails.addActionListener(evt -> {
            setContentPane(detailsPanel);
            revalidate();
            repaint();
        });

        jCheckBoxMenuItemDark.setSelected(false); // uncheck dark mode

        jMenuItemPreferences.addActionListener(evt -> showEditPanel());
        jMenuSettings.add(jMenuItemPreferences);

        ButtonGroup formatGroup = new ButtonGroup();
        formatGroup.add(jRadioButtonMP3);
        formatGroup.add(jRadioButtonMP4);
        jRadioButtonMP4.setSelected(true);

        jMenuItemLogout.addActionListener(evt -> {
            TokenManager.deleteToken();
            TokenManager.deleteCredentials();
            showLoginPanel();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDownload = new javax.swing.JTextArea();
        jButtonReproduce = new javax.swing.JButton();
        jRadioButtonMP3 = new javax.swing.JRadioButton();
        jRadioButtonMP4 = new javax.swing.JRadioButton();
        jButtonDetails = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jCheckBoxMenuItemDark = new javax.swing.JCheckBoxMenuItem();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(650, 0, 140, 140);

        jLabelTitle.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabelTitle.setText("DOWNLOAD WITHOUT ADS!");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(140, 30, 350, 40);

        jTextFieldLink.setToolTipText("");
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLink);
        jTextFieldLink.setBounds(150, 100, 280, 30);

        jButtonSearch.setText("Go");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(430, 100, 50, 30);
        getContentPane().add(jProgressBar);
        jProgressBar.setBounds(150, 170, 330, 20);

        jTextAreaDownload.setColumns(20);
        jTextAreaDownload.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDownload);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 220, 700, 230);

        jButtonReproduce.setText("Reproduce");
        jButtonReproduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproduceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReproduce);
        jButtonReproduce.setBounds(310, 470, 130, 20);

        jRadioButtonMP3.setText(".mp3");
        getContentPane().add(jRadioButtonMP3);
        jRadioButtonMP3.setBounds(150, 140, 50, 21);

        jRadioButtonMP4.setText(".mp4");
        getContentPane().add(jRadioButtonMP4);
        jRadioButtonMP4.setBounds(260, 140, 50, 21);

        jButtonDetails.setText("Details");
        jButtonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDetails);
        jButtonDetails.setBounds(590, 170, 110, 23);

        jMenuExit.setText("File");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        jMenuSettings.setText("Edit");

        jCheckBoxMenuItemDark.setSelected(true);
        jCheckBoxMenuItemDark.setText("Dark/Clear");
        jCheckBoxMenuItemDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDarkActionPerformed(evt);
            }
        });
        jMenuSettings.add(jCheckBoxMenuItemDark);

        jMenuItemPreferences.setText("Preferences");
        jMenuSettings.add(jMenuItemPreferences);

        jMenuBar1.add(jMenuSettings);

        jMenu1.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showEditPanel() {
        setContentPane(editPanel);
        revalidate();
        repaint();
    }

    private void showLoginPanel() {
        setContentPane(loginPanel);
        revalidate();
        repaint();
    }

    private void showMainPanel() {
        setContentPane(mainPanel);
        revalidate();
        repaint();
    }

    private boolean tryAutoLogin() {
        String token = TokenManager.loadToken();
        if (token != null && TokenManager.validate(token)) {
            showMainPanel();
            return true;
        }
        return false;
    }

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        AboutDialog about = new AboutDialog(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String url = jTextFieldLink.getText().trim();

        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid video link.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String format;
        if (jRadioButtonMP3.isSelected()) {
            format = "bestaudio";
        } else if (jRadioButtonMP4.isSelected()) {
            format = "bestvideo+bestaudio";
        } else {
            JOptionPane.showMessageDialog(this, "Please select MP3 or MP4 format.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Prevent multiple downloads at once
        jButtonSearch.setEnabled(false);
        jProgressBar.setValue(0);
        jTextAreaDownload.setText("Preparing download...\n");

        // Path to yt-dlp.exe
        String ytDlpPath = "C:\\Users\\nuria\\AppData\\Local\\yt-dlp\\yt-dlp.exe";

        // Output folder (Downloads)
        String outputDir = System.getProperty("user.home") + "\\Downloads";

        new DownloadWorker(ytDlpPath, url, outputDir, format).execute();

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    private void jCheckBoxMenuItemDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDarkActionPerformed

    }//GEN-LAST:event_jCheckBoxMenuItemDarkActionPerformed

    private void jButtonReproduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproduceActionPerformed
        if (lastDownloadedFile != null && lastDownloadedFile.exists()) {
            try {
                java.awt.Desktop.getDesktop().open(lastDownloadedFile);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Unable to open file:\n" + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "There is nothing to show.", "No Video",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }//GEN-LAST:event_jButtonReproduceActionPerformed

    private void jButtonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetailsActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    private class DownloadWorker extends javax.swing.SwingWorker<Void, String> {

        private final String ytDlpPath;
        private final String url;
        private final String outputDir;
        private final String format;

        public DownloadWorker(String ytDlpPath, String url, String outputDir, String format) {
            this.ytDlpPath = ytDlpPath;
            this.url = url;
            this.outputDir = outputDir;
            this.format = format;
        }

        @Override
        protected Void doInBackground() {
            try {
                String ext = format.equals("bestaudio") ? "mp3" : "mp4";
                ProcessBuilder builder = new ProcessBuilder(
                        ytDlpPath,
                        "-f", format,
                        "--extract-audio",
                        "--audio-format", "mp3",
                        "--output", outputDir + "/%(title)s." + ext,
                        url
                );

                // Remove audio-extract flags if downloading MP4
                if (!format.equals("bestaudio")) {
                    builder.command().remove("--extract-audio");
                    builder.command().remove("--audio-format");
                    builder.command().remove("mp3");
                }

                builder.redirectErrorStream(true);
                Process process = builder.start();

                try (java.io.BufferedReader reader = new java.io.BufferedReader(
                        new java.io.InputStreamReader(process.getInputStream(), "UTF-8"))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        publish(line);
                        if (line.contains("%")) {
                            String percent = line.replaceAll(".*?(\\d{1,3}\\.\\d)%.*", "$1");
                            try {
                                int progress = (int) Float.parseFloat(percent);
                                setProgress(progress);
                            } catch (NumberFormatException ignored) {
                            }
                        }
                    }
                }
                process.waitFor();
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.SwingUtilities.invokeLater(()
                        -> JOptionPane.showMessageDialog(Main.this, "Error during download:\n" + ex.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE)
                );
            }
            return null;
        }

        @Override
        protected void process(java.util.List<String> lines) {
            for (String line : lines) {
                jTextAreaDownload.append(line + "\n");
            }
            jProgressBar.setValue(getProgress());
        }

        @Override
        protected void done() {
            jProgressBar.setValue(100);
            jButtonSearch.setEnabled(true);
            jTextAreaDownload.append("\n✅ Download completed successfully!\n");

            //Detect the latest downloaded video file
            java.io.File folder = new java.io.File(outputDir);
            java.io.File[] files = folder.listFiles((dir, name)
                    -> name.endsWith(".mp4")); //|| name.endsWith(".mkv") || name.endsWith(".webm"));
            if (files != null && files.length > 0) {
                java.util.Arrays.sort(files, java.util.Comparator.comparingLong(java.io.File::lastModified).reversed());
                lastDownloadedFile = files[0]; // most recent video
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonReproduce;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDark;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonMP3;
    private javax.swing.JRadioButton jRadioButtonMP4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDownload;
    private javax.swing.JTextField jTextFieldLink;
    // End of variables declaration//GEN-END:variables
}
