/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrover.antiads;

import adrover.antiads.panels.EditPanel;
import adrover.antiads.panels.DetailsPanel;
import adrover.antiads.dialogs.AboutDialog;
import adrover.antiads.login.LoginPanel;
import adrover.antiads.use.AppColor;
import adrover.mediacomponent.ApiClient.Media;
import adrover.mediacomponent.MediaEvent;
import adrover.mediacomponent.MediaListener;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Main window of the AdVoid application.
 * <p>
 * This class extends {@link javax.swing.JFrame} and acts as the main controller
 * of the graphical user interface. It is responsible for:
 * </p>
 * <ul>
 * <li>Managing navigation between panels (login, details, edit)</li>
 * <li>Handling dark/light theme switching</li>
 * <li>Downloading multimedia content</li>
 * <li>Playing the last downloaded file</li>
 * </ul>
 *
 * <p>
 * The interface automatically resizes its components when the window size
 * changes.
 * </p>
 *
 * @author Nuria
 * @version 1.0
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Application logger used to register errors and relevant events.
     */
    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Main application panel.
     */
    public javax.swing.JPanel mainPanel;

    /**
     * Preferences editing panel.
     */
    private EditPanel editPanel;

    /**
     * Last downloaded media file.
     */
    private java.io.File lastDownloadedFile;

    /**
     * Media details panel.
     */
    private DetailsPanel detailsPanel;

    /**
     * Login panel.
     */
    private LoginPanel loginPanel;

    /**
     * Base window size used for automatic resizing.
     */
    private final Dimension baseSize = new Dimension(800, 600);

    /**
     * Stores the original bounds of all UI components.
     */
    private final Map<Component, Rectangle> baseBounds = new HashMap<>();

    /**
     * Indicates whether dark mode is enabled.
     */
    private boolean darkMode = false;

    /**
     * Main window constructor.
     * <p>
     * Initializes UI components, applies styles, creates secondary panels and
     * handles automatic login if a saved token exists.
     * </p>
     */
    public Main() {
        initComponents();
        this.setSize(800, 600);
        setLocationRelativeTo(this);
        enableAutoResize();
        this.setMinimumSize(new Dimension(800, 600));
        setTitle("AdVoid");
        mainPanel = (JPanel) getContentPane();

        styleComponents();
        applyTheme(darkMode);
        jCheckBoxMenuItemDark.setSelected(darkMode);

        // Inicializar paneles
        detailsPanel = new DetailsPanel(mediaComponent1, darkMode);
        editPanel = new EditPanel(darkMode);
        loginPanel = new LoginPanel(this, mediaComponent1);

        mediaComponent1.addMediaListener(new MediaListener() {
            @Override
            public void newMediaAdded(MediaEvent event) {
                System.out.println(" NUEVO EVENTO: Nuevos archivos detectados:");
                for (Media m : event.getNewMedia()) {
                    System.out.print("-" + m.mediaFileName);
                }
                System.out.print("Fecha: " + event.getTimestamp());
            }
        });
        // Auto-login
        String savedToken = loginPanel.getSavedToken();

        if (savedToken != null && !savedToken.isBlank()) {
            startWithToken(savedToken);
        } else {
            showLoginPanel();
        }

        jButtonDetails.addActionListener(evt -> {
            setContentPane(detailsPanel);
            revalidate();
            repaint();
        });

        jCheckBoxMenuItemDark.setSelected(false);

        jMenuItemPreferences.addActionListener(evt -> showEditPanel());
        jMenuSettings.add(jMenuItemPreferences);

        ButtonGroup formatGroup = new ButtonGroup();
        formatGroup.add(jRadioButtonMP3);
        formatGroup.add(jRadioButtonMP4);
        jRadioButtonMP4.setSelected(true);

        jMenuItemLogout.addActionListener(evt -> {
            loginPanel.clearSavedAuth();
            showLoginPanel();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDownload = new javax.swing.JTextArea();
        jButtonReproduce = new javax.swing.JButton();
        jRadioButtonMP3 = new javax.swing.JRadioButton();
        jRadioButtonMP4 = new javax.swing.JRadioButton();
        jButtonDetails = new javax.swing.JButton();
        mediaComponent1 = new adrover.mediacomponent.MediaComponent();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jCheckBoxMenuItemDark = new javax.swing.JCheckBoxMenuItem();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(650, 0, 140, 140);

        jLabelTitle.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabelTitle.setText("DOWNLOAD WITHOUT ADS!");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(130, 30, 350, 40);

        jTextFieldLink.setToolTipText("");
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLink);
        jTextFieldLink.setBounds(120, 100, 310, 30);

        jButtonSearch.setText("Go");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(430, 100, 70, 30);
        getContentPane().add(jProgressBar);
        jProgressBar.setBounds(150, 170, 330, 20);

        jTextAreaDownload.setColumns(20);
        jTextAreaDownload.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDownload);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 220, 700, 230);

        jButtonReproduce.setText("Reproduce");
        jButtonReproduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproduceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReproduce);
        jButtonReproduce.setBounds(310, 470, 130, 20);

        jRadioButtonMP3.setText(".mp3");
        getContentPane().add(jRadioButtonMP3);
        jRadioButtonMP3.setBounds(150, 140, 80, 21);

        jRadioButtonMP4.setText(".mp4");
        getContentPane().add(jRadioButtonMP4);
        jRadioButtonMP4.setBounds(260, 140, 80, 21);

        jButtonDetails.setText("Details");
        jButtonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDetails);
        jButtonDetails.setBounds(590, 170, 110, 23);

        mediaComponent1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mediaComponent1.setApiUrl("https://difreenet9.azurewebsites.net");
        mediaComponent1.setToken("");
        getContentPane().add(mediaComponent1);
        mediaComponent1.setBounds(30, 50, 40, 40);

        jMenuExit.setText("File");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        jMenuSettings.setText("Edit");

        jCheckBoxMenuItemDark.setSelected(true);
        jCheckBoxMenuItemDark.setText("Dark/Clear");
        jCheckBoxMenuItemDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDarkActionPerformed(evt);
            }
        });
        jMenuSettings.add(jCheckBoxMenuItemDark);

        jMenuItemPreferences.setText("Preferences");
        jMenuSettings.add(jMenuItemPreferences);

        jMenuBar1.add(jMenuSettings);

        jMenu1.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Applies fonts and visual styles to the main UI components.
     */
    private void styleComponents() {
        // ==== Fonts modernas ====
        Font titleFont = new Font("Segoe UI", Font.BOLD, 22);
        Font labelFont = new Font("Segoe UI", Font.PLAIN, 16);
        Font buttonFont = new Font("Segoe UI", Font.BOLD, 16);

        // ==== Labels ====
        jLabelTitle.setFont(titleFont);
        jLabelTitle.setForeground(darkMode ? Color.WHITE : Color.DARK_GRAY);

        jLabelLogo.setOpaque(false);

        // ==== Buttons ====
        JButton[] buttons = {jButtonSearch, jButtonReproduce, jButtonDetails};
        for (JButton b : buttons) {
            b.setFont(buttonFont);
            b.setForeground(Color.WHITE);
            b.setBackground(new Color(60, 150, 250));
            b.setFocusPainted(false);
            b.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            b.setOpaque(true);
        }

        // ==== TextFields y TextArea ====
        jTextFieldLink.setFont(labelFont);
        jTextAreaDownload.setFont(labelFont);
        jTextAreaDownload.setLineWrap(true);
        jTextAreaDownload.setWrapStyleWord(true);
    }

    /**
     * Applies the selected visual theme to the interface.
     *
     * @param darkMode {@code true} to enable dark mode, {@code false} to enable
     * light mode
     */
    private void applyTheme(boolean darkMode) {

        java.awt.Color bg = darkMode ? AppColor.DARK_BG : AppColor.LIGHT_BG;
        java.awt.Color panel = darkMode ? AppColor.DARK_PANEL : AppColor.LIGHT_PANEL;
        java.awt.Color btn = darkMode ? AppColor.DARK_BUTTON : AppColor.LIGHT_BUTTON;
        java.awt.Color text = darkMode ? AppColor.DARK_TEXT : AppColor.LIGHT_TEXT;

        // Fondo principal
        getContentPane().setBackground(bg);

        // Labels
        jLabelTitle.setForeground(text);

        // TextField
        jTextFieldLink.setBackground(panel);
        jTextFieldLink.setForeground(text);

        // TextArea + Scroll
        jTextAreaDownload.setBackground(panel);
        jTextAreaDownload.setForeground(text);
        jScrollPane1.getViewport().setBackground(panel);

        // Progress bar
        jProgressBar.setBackground(panel);
        jProgressBar.setForeground(btn);

        // Botones
        jButtonSearch.setBackground(btn);
        jButtonSearch.setForeground(text);

        jButtonReproduce.setBackground(btn);
        jButtonReproduce.setForeground(text);

        jButtonDetails.setBackground(btn);
        jButtonDetails.setForeground(text);

        // Radio buttons
        jRadioButtonMP3.setBackground(bg);
        jRadioButtonMP3.setForeground(text);

        jRadioButtonMP4.setBackground(bg);
        jRadioButtonMP4.setForeground(text);

        // Progress bar
        jProgressBar.setMinimum(0);
        jProgressBar.setMaximum(100);
        jProgressBar.setStringPainted(true);

        repaint();
    }

    /**
     * Enables automatic resizing of UI components when the window size changes.
     */
    private void enableAutoResize() {

        // Guardar bounds originales de todos los componentes
        for (Component c : getContentPane().getComponents()) {
            baseBounds.put(c, c.getBounds());
        }

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {

                double scaleX = getWidth() / (double) baseSize.width;
                double scaleY = getHeight() / (double) baseSize.height;

                for (Map.Entry<Component, Rectangle> entry : baseBounds.entrySet()) {

                    Component c = entry.getKey();
                    Rectangle r = entry.getValue();

                    int newX = (int) (r.x * scaleX);
                    int newY = (int) (r.y * scaleY);
                    int newW = (int) (r.width * scaleX);
                    int newH = (int) (r.height * scaleY);

                    c.setBounds(newX, newY, newW, newH);
                }

                getContentPane().revalidate();
                getContentPane().repaint();
            }
        });
    }

    /**
     * Starts the application using a stored authentication token.
     *
     * @param token saved authentication token
     */
    public void startWithToken(String token) {

        if (token == null || token.isBlank()) {
            showLoginPanel();
            return;
        }

        detailsPanel.loadAllMedia();
        showMainPanel();
    }

    /**
     * Displays the media details panel. If the user is not authenticated, the
     * login panel is shown.
     */
    public void showDetailsPanel() {
        if (mediaComponent1.getToken() == null || mediaComponent1.getToken().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "You must login first",
                    "Error 401", JOptionPane.ERROR_MESSAGE);
            showLoginPanel();
            return;
        }

        detailsPanel.loadAllMedia(); // refresca la lista con media actual
        setContentPane(detailsPanel);
        detailsPanel.applyTheme(darkMode);
        revalidate();
        repaint();
    }

    /**
     * Displays the preferences editing panel.
     */
    public void showEditPanel() {
        setContentPane(editPanel);
        editPanel.applyTheme(darkMode);
        revalidate();
        repaint();
    }

    /**
     * Displays the login panel.
     */
    private void showLoginPanel() {
        setContentPane(loginPanel);
        loginPanel.applyTheme(darkMode);
        revalidate();
        repaint();
    }

    /**
     * Displays the main application panel.
     */
    public void showMainPanel() {
        setContentPane(mainPanel);
        applyTheme(darkMode);
        revalidate();
        repaint();
    }


    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        AboutDialog about = new AboutDialog(this, true, jCheckBoxMenuItemDark.isSelected());
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String url = jTextFieldLink.getText().trim();

        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid video link.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String format;
        if (jRadioButtonMP3.isSelected()) {
            format = "bestaudio";
        } else if (jRadioButtonMP4.isSelected()) {
            format = "bestvideo";
        } else {
            JOptionPane.showMessageDialog(this, "Please select MP3 or MP4 format.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Prevent multiple downloads at once
        jProgressBar.setValue(0);
        jTextAreaDownload.setText("Preparing download...\n");

        // Path to yt-dlp.exe
        String ytDlpPath = editPanel.getYtDlpPath();
        if (ytDlpPath.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please select the yt-dlp executable path",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Output folder (Downloads)
        String outputDir = System.getProperty("user.home") + "\\Downloads";

        new DownloadWorker(ytDlpPath, url, outputDir, format).execute();

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    private void jCheckBoxMenuItemDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDarkActionPerformed
        darkMode = jCheckBoxMenuItemDark.isSelected();

        // Main
        applyTheme(darkMode);

        // Paneles
        loginPanel.applyTheme(darkMode);
        detailsPanel.applyTheme(darkMode);

        repaint();

    }//GEN-LAST:event_jCheckBoxMenuItemDarkActionPerformed

    private void jButtonReproduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproduceActionPerformed
        if (lastDownloadedFile != null && lastDownloadedFile.exists()) {
            try {
                java.awt.Desktop.getDesktop().open(lastDownloadedFile);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Unable to open file:\n" + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "There is nothing to show.", "No Video",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Application entry point.
     *
     * @param args command-line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));

    }//GEN-LAST:event_jButtonReproduceActionPerformed

    private void jButtonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetailsActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    /**
     * Background task responsible for downloading multimedia content using the
     * external yt-dlp tool.
     */
    private class DownloadWorker extends javax.swing.SwingWorker<Void, String> {

        /**
         * Path to the yt-dlp executable.
         */
        private final String ytDlpPath;

        /**
         * Video URL to download.
         */
        private final String url;

        /**
         * Output directory for the downloaded file.
         */
        private final String outputDir;

        /**
         * Download format (audio or video).
         */
        private final String format;

        /**
         * Creates a new download worker.
         *
         * @param ytDlpPath path to yt-dlp executable
         * @param url video URL
         * @param outputDir output directory
         * @param format selected format
         */
        public DownloadWorker(String ytDlpPath, String url,
                String outputDir, String format) {
            this.ytDlpPath = ytDlpPath;
            this.url = url;
            this.outputDir = outputDir;
            this.format = format;
        }

        /**
         * Executes the download process in the background.
         *
         * @return {@code null} when the task finishes
         */
        @Override
        protected Void doInBackground() {
            try {
                String ext = format.equals("bestaudio") ? "mp3" : "mp4";
                ProcessBuilder builder = new ProcessBuilder(
                        ytDlpPath,
                        "-f", format,
                        "--extract-audio",
                        "--audio-format", "mp3",
                        "--output", outputDir + "/%(title)s." + ext,
                        url
                );

                // Remove audio-extract flags if downloading MP4
                if (!format.equals("bestaudio")) {
                    builder.command().remove("--extract-audio");
                    builder.command().remove("--audio-format");
                    builder.command().remove("mp3");
                }

                builder.redirectErrorStream(true);
                Process process = builder.start();

                try (java.io.BufferedReader reader = new java.io.BufferedReader(
                        new java.io.InputStreamReader(process.getInputStream(), "UTF-8"))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        publish(line);
                        if (line.contains("%")) {
                            String percent = line.replaceAll(".*?(\\d{1,3}\\.\\d)%.*", "$1");
                            try {
                                int progress = (int) Float.parseFloat(percent);
                                setProgress(progress);
                            } catch (NumberFormatException ignored) {
                            }
                        }
                    }
                }
                process.waitFor();
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        JOptionPane.showMessageDialog(Main.this, "Error during download:\n" + ex.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                });
            }
            return null;
        }

        /**
         * Processes intermediate output produced by the download task.
         * <p>
         * Each received line is appended to the download log text area and the
         * progress bar is updated accordingly.
         * </p>
         *
         * @param lines list of output lines generated by yt-dlp
         */
        @Override
        protected void process(java.util.List<String> lines) {
            for (String line : lines) {
                jTextAreaDownload.append(line + "\n");
            }
            jProgressBar.setValue(getProgress());
        }

        /**
         * Executed when the background download task finishes.
         * <p>
         * Re-enables the download button, updates the progress bar, displays a
         * completion message and detects the most recently downloaded media
         * file.
         * </p>
         */
        @Override
        protected void done() {
            jProgressBar.setValue(100);
            jButtonSearch.setEnabled(true);
            jTextAreaDownload.append("\n✅ Download completed successfully!\n");

            //Detect the latest downloaded video file
            java.io.File folder = new java.io.File(outputDir);
            java.io.File[] files = folder.listFiles((dir, name)
                    -> name.endsWith(".mp4"));
            if (files != null && files.length > 0) {
                java.util.Arrays.sort(files, java.util.Comparator.comparingLong(java.io.File::lastModified).reversed());
                lastDownloadedFile = files[0]; // most recent video
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonReproduce;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDark;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonMP3;
    private javax.swing.JRadioButton jRadioButtonMP4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDownload;
    private javax.swing.JTextField jTextFieldLink;
    private adrover.mediacomponent.MediaComponent mediaComponent1;
    // End of variables declaration//GEN-END:variables
}
