/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrover.antiads;

import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    private Main main;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setSize(800, 600);
         setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jLabelDownload = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jCheckBoxMenuItemDark = new javax.swing.JCheckBoxMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(650, 0, 140, 140);

        jLabelTitle.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabelTitle.setText("DOWNLOAD WITHOUT ADS!");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(140, 30, 350, 40);

        jTextFieldLink.setToolTipText("");
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLink);
        jTextFieldLink.setBounds(150, 100, 280, 30);

        jButtonSearch.setText("Go");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(430, 100, 50, 30);
        getContentPane().add(jProgressBar);
        jProgressBar.setBounds(150, 170, 330, 20);

        jLabelDownload.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabelDownload);
        jLabelDownload.setBounds(150, 220, 340, 150);

        jMenuExit.setText("X");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        jMenuSettings.setText("Settings");

        jCheckBoxMenuItemDark.setSelected(true);
        jCheckBoxMenuItemDark.setText("Dark/Clear");
        jMenuSettings.add(jCheckBoxMenuItemDark);

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemAbout);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
       JOptionPane.showMessageDialog(this,
                "Developed by Nuria Adrover\n"
                + "Course: 2º DAM \n"
                + "Resources used:\n"
                + "- Logo: LogoDesigner\n"
                + "- Other resources: Teacher, Classmates, ChatGPT");
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDark;
    private javax.swing.JLabel jLabelDownload;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jTextFieldLink;
    // End of variables declaration//GEN-END:variables
}
